baseurl = "/"
languageCode = "en-us"
title = "Digital Content Update & Writing Workshop"

[Params]
	presentationsubtitle = "NIPC Meeting, San Diego, CA"
	presentationdate = "2017-02-11"
	usefontawesome = true
	authorbyline = "Ryan Watters, ELS; Digital Content Manager"
