baseurl = "/"
languageCode = "en-us"
title = "CAP.org Membership New Editorial Model"

[Params]
	presentationsubtitle = "PHC, June 2017"
	presentationdate = "2017-06-01"
	usefontawesome = true
	authorbyline = "Ryan Watters, ELS; Digital Content Manager"
