baseurl = "/"
languageCode = "en-us"
title = "CAP.org Membership New Editorial Model"

[Params]
	presentationsubtitle = "Introduction for PHC"
	presentationdate = "2017-04-21"
	usefontawesome = true
	authorbyline = "Ryan Watters, ELS; Digital Content Manager"
