baseurl = "/"
languageCode = "en-us"
title = "CAP.org Member-generated Content"

[Params]
	presentationsubtitle = "Introduction, New Editorial Model"
	presentationdate = "2017-06-23"
	usefontawesome = true
	authorbyline = "Ryan Watters; Digital Content Manager"
	siteurl = "https://phc.netlify.com"
	sections = [ "one","two", "three"]
